/**
 * 错误代码和消息常量
 */

export const ERROR_CODES = {
  // 通用错误
  UNKNOWN_ERROR: 'UNKNOWN_ERROR',
  INVALID_INPUT: 'INVALID_INPUT',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  TIMEOUT_ERROR: 'TIMEOUT_ERROR',
  PERMISSION_DENIED: 'PERMISSION_DENIED',
  RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',
  RESOURCE_ALREADY_EXISTS: 'RESOURCE_ALREADY_EXISTS',

  // 函数相关错误
  FUNCTION_NOT_FOUND: 'FUNCTION_NOT_FOUND',
  FUNCTION_EXECUTION_ERROR: 'FUNCTION_EXECUTION_ERROR',
  FUNCTION_VALIDATION_ERROR: 'FUNCTION_VALIDATION_ERROR',
  FUNCTION_TIMEOUT: 'FUNCTION_TIMEOUT',
  FUNCTION_DEPENDENCY_ERROR: 'FUNCTION_DEPENDENCY_ERROR',

  // Agent相关错误
  AGENT_NOT_FOUND: 'AGENT_NOT_FOUND',
  AGENT_EXECUTION_ERROR: 'AGENT_EXECUTION_ERROR',
  AGENT_UNAVAILABLE: 'AGENT_UNAVAILABLE',
  AGENT_CAPABILITY_ERROR: 'AGENT_CAPABILITY_ERROR',

  // 插件相关错误
  PLUGIN_NOT_FOUND: 'PLUGIN_NOT_FOUND',
  PLUGIN_LOAD_ERROR: 'PLUGIN_LOAD_ERROR',
  PLUGIN_INITIALIZATION_ERROR: 'PLUGIN_INITIALIZATION_ERROR',
  PLUGIN_DEPENDENCY_ERROR: 'PLUGIN_DEPENDENCY_ERROR',
  PLUGIN_CONFLICT_ERROR: 'PLUGIN_CONFLICT_ERROR',

  // 记忆相关错误
  MEMORY_ERROR: 'MEMORY_ERROR',
  MEMORY_STORAGE_ERROR: 'MEMORY_STORAGE_ERROR',
  MEMORY_RETRIEVAL_ERROR: 'MEMORY_RETRIEVAL_ERROR',
  MEMORY_CLEANUP_ERROR: 'MEMORY_CLEANUP_ERROR',

  // 注册中心相关错误
  REGISTRY_ERROR: 'REGISTRY_ERROR',
  REGISTRATION_ERROR: 'REGISTRATION_ERROR',
  UNREGISTRATION_ERROR: 'UNREGISTRATION_ERROR',

  // 编排相关错误
  ORCHESTRATION_ERROR: 'ORCHESTRATION_ERROR',
  WORKFLOW_ERROR: 'WORKFLOW_ERROR',
  TASK_ERROR: 'TASK_ERROR',
  COORDINATION_ERROR: 'COORDINATION_ERROR',
} as const;

export const ERROR_MESSAGES = {
  [ERROR_CODES.UNKNOWN_ERROR]: '发生了未知错误',
  [ERROR_CODES.INVALID_INPUT]: '输入参数无效',
  [ERROR_CODES.VALIDATION_ERROR]: '数据验证失败',
  [ERROR_CODES.TIMEOUT_ERROR]: '操作超时',
  [ERROR_CODES.PERMISSION_DENIED]: '权限不足',
  [ERROR_CODES.RESOURCE_NOT_FOUND]: '资源未找到',
  [ERROR_CODES.RESOURCE_ALREADY_EXISTS]: '资源已存在',

  [ERROR_CODES.FUNCTION_NOT_FOUND]: '函数未找到',
  [ERROR_CODES.FUNCTION_EXECUTION_ERROR]: '函数执行失败',
  [ERROR_CODES.FUNCTION_VALIDATION_ERROR]: '函数参数验证失败',
  [ERROR_CODES.FUNCTION_TIMEOUT]: '函数执行超时',
  [ERROR_CODES.FUNCTION_DEPENDENCY_ERROR]: '函数依赖错误',

  [ERROR_CODES.AGENT_NOT_FOUND]: 'Agent未找到',
  [ERROR_CODES.AGENT_EXECUTION_ERROR]: 'Agent执行失败',
  [ERROR_CODES.AGENT_UNAVAILABLE]: 'Agent不可用',
  [ERROR_CODES.AGENT_CAPABILITY_ERROR]: 'Agent能力不足',

  [ERROR_CODES.PLUGIN_NOT_FOUND]: '插件未找到',
  [ERROR_CODES.PLUGIN_LOAD_ERROR]: '插件加载失败',
  [ERROR_CODES.PLUGIN_INITIALIZATION_ERROR]: '插件初始化失败',
  [ERROR_CODES.PLUGIN_DEPENDENCY_ERROR]: '插件依赖错误',
  [ERROR_CODES.PLUGIN_CONFLICT_ERROR]: '插件冲突',

  [ERROR_CODES.MEMORY_ERROR]: '记忆系统错误',
  [ERROR_CODES.MEMORY_STORAGE_ERROR]: '记忆存储错误',
  [ERROR_CODES.MEMORY_RETRIEVAL_ERROR]: '记忆检索错误',
  [ERROR_CODES.MEMORY_CLEANUP_ERROR]: '记忆清理错误',

  [ERROR_CODES.REGISTRY_ERROR]: '注册中心错误',
  [ERROR_CODES.REGISTRATION_ERROR]: '注册失败',
  [ERROR_CODES.UNREGISTRATION_ERROR]: '注销失败',

  [ERROR_CODES.ORCHESTRATION_ERROR]: '编排错误',
  [ERROR_CODES.WORKFLOW_ERROR]: '工作流错误',
  [ERROR_CODES.TASK_ERROR]: '任务错误',
  [ERROR_CODES.COORDINATION_ERROR]: '协调错误',
} as const;

export function getErrorMessage(code: string): string {
  return (
    ERROR_MESSAGES[code as keyof typeof ERROR_MESSAGES] ||
    ERROR_MESSAGES[ERROR_CODES.UNKNOWN_ERROR]
  );
}
